# Generated by Django 3.0.8 on 2020-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
