# Generated by Django 2.2.2 on 2019-09-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_backgroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='backgroundImage',
            new_name='background_image',
        ),
    ]
