# Generated by Django 3.0.8 on 2020-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_upcoming_events_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_program_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
