# Generated by Django 3.0.8 on 2020-08-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_featured_program_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='featured_program_title',
            new_name='program_slider_title',
        ),
    ]
