# Generated by Django 2.2.2 on 2019-10-25 22:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0003_auto_20190926_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('program_slider_text', models.CharField(max_length=350)),
                ('program_slider', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_slider', to='home.HomePage')),
                ('program_slider_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
