# Generated by Django 3.0.8 on 2020-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200820_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_two_ext_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to an external page instead of a wagtail page'),
        ),
    ]
