# Generated by Django 2.2.2 on 2019-10-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_programslider_program_slider_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programslider',
            name='program_slider_text',
        ),
    ]
