# Generated by Django 2.2.2 on 2019-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191107_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecommends',
            name='read_watch_listen',
            field=models.CharField(choices=[('R', 'read'), ('W', 'watch'), ('L', 'listen')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
