# Generated by Django 2.2.9 on 2020-01-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_staffrecommends_read_watch_listen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecommends',
            name='read_watch_listen',
        ),
    ]
