# Generated by Django 2.2.9 on 2020-01-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0009_remove_staffrecommends_read_watch_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='newsletter_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
